staging_auto_scraper:
  hostname: 144.217.182.183
  user: root
  port: 22
  #configFile: ~/.ssh/config
  identityFile: /var/www/airdna_ovh.pem
  forwardAgent: true
  multiplexing: false
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  stage: staging
#  git_tty: false
  branch: master
#  roles:
#    - app
#    - db
  deploy_path: /var/www/html/auto_scraper/
#  extra_param: "foo {{hostname}}"